### PR TITLE
T28 xslt for mods

### LINKED ISSUE #28: xslt to create mods
Use XSLT instead of spaghetti code to map orcid to MODS.

### PR DESCRIPTION
**Pull request by ihardy**
resolves #28 replaces kludgy citation parsing with an XSL template from Aaron.

### CODE REVIEW

**Comment by dongourley** [comment]
Testing looks good -- except one thing. The (parenthetical part) of the titleinfo is supposed to be the faculty's department (see [Pat Aufderheide](https://auislandora.wrlc.org/islandora/object/auislandora%3A68465?solr_nav%5Bid%5D=1b6d5733f3baf6ff10dd&solr_nav%5Bpage%5D=0&solr_nav%5Boffset%5D=4)) not position (see [Stefan Kramer](https://auislandora-dev.wrlc.org/islandora/object/auislandora%3A1722))

Also, probably not related to this merge and more a Q for @krebeck , but why do I only see 10 citations on [Stefan's citations page](https://auislandora-dev.wrlc.org/islandora/object/auislandora%3A1722/citations) when you created I think 17?

**Comment by krebeck** [comment]
Currently set to only display the most recently modified 10 objects.  I can change the number of objects and the sort order (recently added vs. recently modified).

**Comment by dongourley** [comment]
> I can change the number of objects and the sort order (recently added vs. recently modified).

No, its fine. I was just curious. I imagine there is a search that can be done to see all the associated citations ... by ORCID?

**Comment by ihardy** [comment]
The parenthetical part of titleInfo.title is coming straight from the request JSON, which looks like this: ..."Stefan Kramer (Associate Director for Research Data Services)".

I don't see department in the request body (below) is that something you can pass to me, or something I need to fetch from ORCID?

```json
{
  "identifier": {
    "u1": "0000-0001-5795-7629",
    "netid": "email@email.email"
  },
  "authority": {
    "name": {
      "given": "Stefan",
      "family": "Kramer"
    },
    "titleInfo": {
      "title": "Stefan Kramer (Associate Director for Research Data Services)"
    }
  },
  "affiliation": {
    "email": "email@email.email",
    "organization": "University Library",
    "position": "Associate Director for Research Data Services"
  },
  "url": [
    "http://www.linkedin.com/in/kramerstefan",
    "http://www.american.edu/profiles/faculty/skramer.cfm"
  ],
  "note": {
    "history": ""
  },
  "citations": "https://pub.orcid.org/v2.0/0000-0001-5795-7629/works/38200592,23792779,10141553,21735530,10141734,10141552,21736035,10141512,10141545,10141563,10141516,10141514,10141520,10141539,10141538,10141685,10141531"
}
```

**Pull request merged**
